spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crisis_db
    username: postgres
    password: Tejumodi@1729
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration